Protect routes and update tests.
neontribe/ARCVService pull request #477
Opened 2022-02-22 14:33 UTC by neonleann

https://trello.com/c/Z4QQdG76/1679-infosec-restrain-our-route-parameters-to-a-type-usually-ints-vv-e

2022-02-22 15:12 UTC, charlesstrange2 requested changes
Got some spaces in places 👾

2022-02-22 15:12 UTC, charlesstrange2 commented on routes/api.php
> +        ]) ->where('trader', '^[0-9]+$');
Remove space between ")" and "->"

2022-02-23 08:40 UTC, neonleann commented on routes/api.php
> +        ]) ->where('trader', '^[0-9]+$');
Silly me. All removed.

2022-02-23 11:32 UTC, charlesstrange2 approved these changes
okeodoke, give it a go

2022-02-23 11:45 UTC, merged