1.13/1744 calculation for children age change and other rules changes for scotland vvv eee
neontribe/ARCVService pull request #490
Opened 2022-03-07 14:23 UTC by neonleann

https://trello.com/c/R9cJkhpP/1744-calculation-for-children-age-change-and-other-rules-changes-for-scotland-vvv-eee
🥴
Notes:
1) I have commented out the code I added so that centres could be created as Scottish. I figured it was better than deleting in case it was needed, but I'll say goodbye to it if I have to.

2) In the two new Scottish rules, I have added code that pretends the start date of school is APR not AUG, and added some if statements to alter the rules accordingly, for when the env is local or staging. I figured this would make life easier for dev and Karl. However, this will only work for this month, because the rules are fairly specific and would need to be altered if you were looking at it next month. Once we're happy with it, I guess these bits can be removed.

3) The above note does not apply to 'testing', as in running the phphunit tests. That has it's own method for pretending it's actually JUL today.

2022-03-07 15:30 UTC, charlesstrange2 requested changes
Some suggestions :-)

2022-03-07 15:30 UTC, charlesstrange2 commented on app/Services/VoucherEvaluator/Evaluations/ScottishChildIsAlmostPrimarySchoolAge.php
> +        \Log::info('age ' . $age);
similar here?

2022-03-07 15:34 UTC, neonleann commented on app/Http/Controllers/Service/Admin/SponsorsController.php
> +// use App\Evaluation;
My mistake. I forgot about the function.

2022-03-07 15:34 UTC, neonleann commented on app/Http/Controllers/Service/Admin/SponsorsController.php
> +    public function scottishFamilyOverrides()
I have added static.

2022-03-07 15:36 UTC, neonleann commented on app/Services/VoucherEvaluator/Evaluations/ScottishChildIsAlmostPrimarySchoolAge.php
> +      \Log::info('ScottishChildIsAlmostPrimarySchoolAge');
Gone.

2022-03-07 15:36 UTC, neonleann commented on app/Services/VoucherEvaluator/Evaluations/ScottishChildIsAlmostPrimarySchoolAge.php
> +        \Log::info('spec ' . $this->specification->isSatisfiedBy($candidate));
Gone.

2022-03-07 15:39 UTC, neonleann commented on database/seeds/SponsorsSeeder.php
> +    public function scottishFamilyOverrides()
They aren't identical, because there's an extra one that had to be added to the controller, that the seeder gets a different way.

2022-03-07 15:40 UTC, neonleann commented on app/Services/VoucherEvaluator/Evaluations/ScottishChildIsAlmostPrimarySchoolAge.php
> +    public $reason = 'is almost primary school age (SCOTLAND)';
https://trello.com/c/ZNYl7ho6/1772-copy-sweep

2022-03-08 09:59 UTC, charlesstrange2 requested changes
as discussed have a look at a change to the way we work out kids age at future date

2022-03-08 09:59 UTC, charlesstrange2 commented on tests/Unit/Services/VoucherEvaluator/ScottishVoucherEvaluatorTest.php
> +        $evaluation = $evaluator->evaluate($this->readyForPrimarySchool);
possibly a scottish child?

2022-03-08 14:55 UTC, merged