1910-duplicate-trader-payment-requests-vvv-ee
neontribe/ARCVService pull request #601
Opened 2023-03-07 15:48 UTC by lauragurney

https://trello.com/c/6i4wVtrb/1910-duplicate-trader-payment-requests-vvv-ee

Code largely lifted from https://github.com/neontribe/ARCVService/compare/1.15/release...1.14/1910-payment-race-conditions

Tested on 44 vouchers in local env

2023-03-07 16:58 UTC, charlesstrange2 requested changes
:wood: :axe:

2023-03-07 16:58 UTC, charlesstrange2 commented on app/Http/Controllers/API/VoucherController.php
> +            \Log::info('No lock for me!');
let's keep this one though...

2023-03-07 17:05 UTC, lauragurney commented on app/Http/Controllers/API/VoucherController.php
> +            \Log::info('I have a lock');
I chopped it

2023-03-09 17:41 UTC, charlesstrange2 approved these changes
okedoke

2023-03-09 17:48 UTC, merged