docs: new tagging proposal
neontribe/ARCVService pull request #670
Opened 2023-06-27 10:41 UTC by tobybatch

2023-07-07 15:05 UTC, karalan commented on README.md
> + * Raise a PR into develop
Need to then pasta the PR into the Trello Card, then move the ticket to awaiting code review

2023-07-07 15:07 UTC, karalan requested changes

2023-07-07 15:07 UTC, karalan commented on README.md
> + * Merge and delete branch
same here, PR needs to go on trello card

2023-09-03 08:51 UTC, neonleann approved these changes
👍

2023-09-08 08:14 UTC, lauragurney approved these changes

2023-10-18 09:11 UTC, merged